### ISSUE TITLE
Страница продукта From the Manufacturer 

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#10]
Не хватает еще одной каритнки там.
Выслал тебе ее мылом. Положи на сервер рядом с уже имеющейся картинкой. При создании продукта я вставлю линк и на эту картинку тоже.

![111](https://cloud.githubusercontent.com/assets/13675953/9114057/826de9ca-3c60-11e5-9f7e-571734d2f365.png)

**Comment by mamont77** [comment]
Добавил. Ее видно здесь http://dev01.rapvokzal.com/product/test-product-please-dont-delete.
Или код

``` html
<img src="/sites/default/themes/hp/images/content/infographic.jpg"/>

```
