### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#11]
В футере не хватает справа блока

![222](https://cloud.githubusercontent.com/assets/13675953/9114800/6132e98c-3c64-11e5-85e4-bc9de025546a.png)

Текст я могу набрать и руками

**Comment by mamont77** [comment]
1. Блок сделал, отредактируешь текст.
2. Кнопку засунул просто картинкой, что бы не писать стили с градиентами и треугольником на фоне. Если необходимо - сделаю на css.
3. Ниже расположил просто картинку с иконками соц сетей. Фон отличается. Потому что вырезан из jpg, который у меня есть в наличии, и который сильно пережат.
