### ISSUE TITLE
Размер овновного контенера

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#2]
Контейнер  .container  должен быть шире
файл greed.less
.container {
    width: 1170px; - это у тебя стоит сейчас. Размер должен быть 1400px иначе слишком узко
}

**Comment by mamont77** [comment]
Ready for testing.

**Comment by vrungel76** [comment]
Верни размер главного контейнера как было - 1170px

**Comment by mamont77** [comment]
Готово.
