### ISSUE TITLE
Хэдер

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#3]
1. На хэдере поле поиска должно быть видно всем. Размер и распооложение привести в соотвествие с макетом.
2. Логотип имеет рамку  - видимо цвет фона не совпадает с фоном рисунка.
3. Фраза "Shop by Department" нужна. Можно совместить с логотипом и пусть будет как картинка.

**Comment by mamont77** [comment]
Я предлагаю переверстать хедер, сделать как ты хочешь. Или максимально близкое к этому. Но сломается отзывчивость (хотя помню, мы решили забить на нее).

![hp - google chrome 08-06-2015 16 07 45](https://cloud.githubusercontent.com/assets/970967/9112148/786eb982-3c55-11e5-8cf0-c2c9d7b9dfb3.png)
Если это тебе  не нужно, то переделываю.

Если отзывчивость все же нужна, то поиграюсь больше с css-ками.

**Comment by vrungel76** [comment]
Я так и не понял как картинку сюда вставлять.
По сути: не нужна отзывчивость. Нужно как в пдф с размерами как на Амазоне )

**Comment by mamont77** [comment]
![issue 3 mamont77 hp-demo - google chrome 08-06-2015 16 35 50](https://cloud.githubusercontent.com/assets/970967/9112758/52bfb7e6-3c59-11e5-9a8f-25487262fd61.png)

**Comment by mamont77** [comment]
По поводу рамки в логотипе. Убрать ее не удается.
Это случилось потому что исходные материалы по факту обычный пережатый jpg. И на краях пиксели гуляют в цвете. Они гуляют и внутри, но это не так бросается в глаза.
Если поставить прозрачный png, то рамки нет.

Они могут прислать нормальный лого?

![cabrioletred](https://cloud.githubusercontent.com/assets/970967/9129584/6a8908c6-3ce2-11e5-944c-03cc6c494fed.png)
![hp - google chrome 08-07-2015 08 57 21](https://cloud.githubusercontent.com/assets/970967/9129585/6a8dea44-3ce2-11e5-9b77-092e24977ad8.png)

Разметка в процессе.

**Comment by mamont77** [comment]
Я в фотошопе логотип затер по краям. Теперь нет рамки.
Шапка готова на проверку.
Хочу обратить внимание что логотип в разных исходных файлах разной версии.
Это здесь видно https://github.com/mamont77/hp-demo/commit/8ebb7ba7c45da2f46c82b067dc49f2c8eec218d8.
