### ISSUE TITLE
Левый блок с чекбоксами - frontpage

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#4]
Шриф не соотвествует - маленький очень. Я тебе присылал пдф где указаны размеры
Файл style.css
Блок:
# block-block-16 .option {  font-size: 12px;  - должно быть 15px

Заголовок блока 15:
# block-block-15 .block-title {  font-size: 16px; должно быть 20px

Текст того же блока 15:
# block-block-15 li {

тут размер наследуется с body - слишком мелкий. Добавь правило  font-size: 15px

**Comment by mamont77** [comment]
Done.

**Comment by mamont77** [comment]
Сделал размеры шрифтов как на амазоне.
