### ISSUE TITLE
Деление темплейта на колонки 

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#5]
Размер всего темплейта: сделай 2/10 а не как щас 3/9 
<aside class="col-sm-2" role="complementary">
<section class="col-sm-10 contextual-links-region">

Не забуть серые полосочки, которые делят отображение по 3 продукта, а так же вертикальную полосоку отделяющую левую секцию от центральной

**Comment by mamont77** [comment]
Готово.
