### ISSUE TITLE
Флажок "Best Seller"

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#6]
Слишком узкий.
<div class="field-name-field-best-seller-text">
Сделай  padding: 7px - общий для всех сторон. 

Цвет - цвет должен быть хэдера!

**Comment by mamont77** [comment]
Fixed.

**Comment by vrungel76** [comment]
Цвет не изменил и уголки

**Comment by mamont77** [comment]
Цвет поменял. 

А с треугольниками сложно возится. Да и не хотелось бы нарезать на фон джипеги, а сделать это на css. В общем это трата времени.

Варианты: 
1. Вернуть padding-top и padding-bottom.
2. Этот вариант никак не годится? http://getbootstrap.com/components/#labels

**Comment by vrungel76** [comment]
::after
.field-name-field-best-seller-text::after {
    border-top-color: #9D9338 !important;
    top: 0px;
    border-width: 14px 8px 0px 11px;
    border-right: 8px dashed rgba(255, 255, 255, 0);
    border-bottom: 0px dashed rgba(255, 255, 255, 0);
    border-left: 11px dashed rgba(255, 255, 255, 0);
    width: 0px;
    height: 0px;
    font-size: 0px;
    line-height: 0;
    transform: translate3d(0px, 0px, 0px);
    content: "";
    position: absolute;
    right: -8px;
    border-style: solid dashed dashed;
}

**Comment by vrungel76** [comment]
befor::
.field-name-field-best-seller-text::before {
    bottom: 0px;
    border-style: dashed dashed solid;
    border-top: 0px dashed rgba(255, 255, 255, 0);
    border-right: 8px dashed rgba(255, 255, 255, 0);
    border-left: 8px dashed rgba(255, 255, 255, 0);
    width: 0px;
    height: 0px;
    font-size: 0px;
    line-height: 0;
    transform: translate3d(0px, 0px, 0px);
    content: "";
    position: absolute;
    border-bottom-color: #9D9338 !important;
    right: -8px;
    border-width: 0px 8px 14px;
}

**Comment by mamont77** [comment]
Тю блин. Ты это имел ввиду. Я почему то решил что ты хочешь закругленное.
Готово.
