### ISSUE TITLE
Подменю под хэдером

### ISSUE THREAD

**Issue by vrungel76** [mamont77/hp-demo#8]
Очень широкое по высоте - маржин в низ тут не нужен.
<section id="block-menu-menu-submenu" class="block block-menu contextual-links-region clearfix">
Убери:
.block {
    margin-bottom: 15px;
}
Не могу найти как сделана тень. Она должна быть еле видна - совсем чуть чуть.

**Comment by mamont77** [comment]
Готово.

**Comment by mamont77** [comment]
Готово.
